proxy:
  secretToken: [TOKEN]
rbac:
  enabled: false
singleuser:
  image:
    name: biosimspace.azurecr.io/jupyter-bss
    tag: bss-v2
  storage:
    type: none
cull:
  timeout: 7200
  every: 600
auth:
  admin:
    users:
      - chris
  whitelist:
    users:
      - chris
      - lester
      - toni
      - charlie
      - adrian
      - julien
