proxy:
  secretToken: [TOKEN]
rbac:
  enabled: false
singleuser:
  image:
    name: biosimspace.azurecr.io/jupyter-bss
    tag: bss-v2
  storage:
    type: none
  memory:
    limit: 1G
    guarantee: 1G
  cpu:
    limit: 1.0
    guarantee: 0.5
  lifecycleHooks:
    postStart:
      exec:
        command: ["ln", "-s", "/home/biosimspace", "."]
cull:
  timeout: 7200
  every: 600
auth:
  admin:
    users:
      - chris
  whitelist:
    users:
      - chris
